apiVersion: v1
kind: Service
metadata:
  name: loggerbuddy-frontend-svc
  namespace: loggerbuddy
spec:
  type: NodePort
  selector:
    app: loggerbuddy-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080